import type { TimelineItem } from "./timeline";

export interface ExportMeta {
  title: string;
  backend: string;
  model?: string;
  cwd?: string;
  exportedAt?: Date;
  /** Unfinished tasks, so a reader knows what is next without reading it all. */
  todos?: string[];
}

/** Fenced blocks in tool output would otherwise break out of their own fence. */
function fence(body: string): string {
  const longest = [...body.matchAll(/`{3,}/g)].reduce(
    (max, match) => Math.max(max, match[0].length),
    2,
  );
  const ticks = "`".repeat(Math.max(3, longest + 1));
  return `${ticks}\n${body}\n${ticks}`;
}

function trim(text: string, limit = 4000, full = false): string {
  const clean = text.replace(/\s+$/, "");
  return !full && clean.length > limit
    ? `${clean.slice(0, limit)}\n… (${clean.length - limit} more characters)`
    : clean;
}

/**
 * Render a transcript as Markdown: one heading per turn, tool calls collapsed
 * into details blocks so the prose stays readable, and permission decisions
 * kept because "what did I let it do" is half the value of an exported log.
 */
export function timelineToMarkdown(
  items: TimelineItem[],
  meta: ExportMeta,
  { full = false }: { full?: boolean } = {},
): string {
  const cut = (text: string, limit?: number) => trim(text, limit, full);
  const when = meta.exportedAt ?? new Date();
  const lines: string[] = [
    `# ${meta.title}`,
    "",
    `- **Agent:** ${meta.backend}${meta.model ? ` (${meta.model})` : ""}`,
    ...(meta.cwd ? [`- **Workspace:** \`${meta.cwd}\``] : []),
    `- **Exported:** ${when.toISOString()}`,
    "",
    ...(meta.todos?.length
      ? ["## Still to do", "", ...meta.todos.map((task) => `- [ ] ${task}`), ""]
      : []),
    "---",
    "",
  ];

  for (const item of items) {
    if (item.kind === "user") {
      lines.push(`## User`, "", cut(item.text), "");
      continue;
    }
    if (item.kind === "assistant") {
      lines.push(`### Assistant`, "", cut(item.text), "");
      continue;
    }
    if (item.kind === "rationale") {
      lines.push(`<details><summary>Reasoning</summary>`, "", cut(item.text), "", `</details>`, "");
      continue;
    }
    if (item.kind === "tool") {
      const args = JSON.stringify(item.args ?? {}, null, 2);
      lines.push(
        `<details><summary>Tool · ${item.name} (${item.status})</summary>`,
        "",
        fence(cut(args, 1500)),
        "",
        ...(item.output ? [fence(cut(item.output))] : []),
        "",
        `</details>`,
        "",
      );
      continue;
    }
    if (item.kind === "notice") {
      lines.push(`> _${item.tone}_: ${cut(item.text, 500)}`, "");
    }
  }

  return `${lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd()}\n`;
}

/** Filesystem-safe, dated filename for the exported transcript. */
export function exportFilename(title: string, at = new Date()): string {
  const slug =
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 48) || "session";
  const stamp = at.toISOString().slice(0, 10);
  return `${slug}-${stamp}.md`;
}

/** Stable per-session name, so the auto-save overwrites instead of piling up. */
export function transcriptFilename(
  identity: string,
  title: string,
): string {
  const slug =
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 40) || "session";
  const id = identity.replace(/[^a-zA-Z0-9]+/g, "").slice(-12) || "session";
  return `${slug}-${id}.md`;
}

/**
 * The message that starts the next agent off. Deliberately not generated by a
 * model: it just points at the file, which already holds the whole session.
 */
export function handoffPrompt(path: string, from: string): string {
  return [
    `Continuing a session that was running on ${from}.`,
    "",
    `Read \`${path}\` first — it is the full transcript of our conversation so far,`,
    "including my instructions, what was decided, and what was already changed.",
    "The working tree is the same one that session was editing, so the code is",
    "already in the state that transcript describes.",
    "",
    "Pick up from the last unfinished task. Do not redo completed work.",
  ].join("\n");
}
